config/routes.rb
Rails.application.routes.draw do
  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_delete
    end
  end

  concern :commentable do |options|
    resources :comments, { only: %i[create], shallow: true }.merge(options)
  end

  devise_for :users

  resources :questions do
    concerns :votable
    concerns :commentable, commentable_type: 'Question'

    resources :answers, shallow: true do
      concerns :votable
      concerns :commentable, commentable_type: 'Answer'

      patch :assign_as_best, on: :member
    end
  end

  resources :attachments, only: %i[destroy]

  resources :links, only: %i[destroy]

  resources :rewards, only: %i[index]

  root to: "questions#index"
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable, Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable

  has_one :reward, dependent: :destroy

  belongs_to :author, class_name: 'User'

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_commit :broadcast_new_question, on: :create

  def assign_reward!(user)
    reward.update!(recipient: user) if reward
  end

  private

  def broadcast_new_question
    BroadcastObjectCreationJob.perform_later("new_question_events", question: self)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :find_question, only: %i[show update destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
    gon.push(question_id: @question.id, answers: @question.answers.ids, current_user: current_user ? current_user.id : 0)
  end

  def new
    @question = current_user.questions.new
    @question.build_reward
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to question_path(@question), notice: 'Question successfully created'
    else
      @question.build_reward unless @question.reward
      render :new
    end
  end

  def update
    if current_user.author_of?(@question)
      @question.update(question_params)
      flash.now.notice = 'Question successfully updated'
    else
      flash.now.alert = "You don't have permission to do that"
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Question successfully deleted'
    else
      redirect_to question_path(@question), alert: "You don't have permission to do that"
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: [:name, :url],
                                     reward_attributes: [:title, :image])
  end

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_edit_form.html.slim
div class='question-errors'
= form_with model: question, class: 'question-edit-form', html: { style: 'display:none;' } do |form|
  div class='form-group'
    = form.label :title, 'Title'
    = form.text_field :title, class: 'form-control'

  div class='form-group'
    = form.label :body, 'Your question'
    = form.text_area :body, class: 'form-control'

  | Links:
  #links.border.p-4.mb-3
    = form.fields_for :links do |link|
      - unless link.object.persisted?
        = render 'links/link_fields', f: link
    span
      = link_to_add_association 'Add link', form, :links, partial: 'links/link_fields'

  | Files:
  .form-group.border.p-4
    = form.file_field :files, multiple: true, direct_upload: true, class: 'form-control-file'

  div
    = form.submit 'Save'

app/views/questions/_question.html.slim
li
  == link_to question.title, question_path(question)

app/views/questions/index.html.slim
h3 Questions
.questions
  ul
    == render @questions

= link_to 'New question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question
h1 Create new Question
= form_with model: @question, local: true do |form|
  div  class='form-group'
    = form.label :title
    = form.text_field :title, class: 'form-control'

  div class='form-group'
    = form.label :body
    = form.text_area :body, class: 'form-control'

  | Links:
  #links.border.p-4.mb-3
    = form.fields_for :links do |link|
      = render 'links/link_fields', f: link
    span
      = link_to_add_association 'Add link', form, :links, partial: 'links/link_fields'

  | Files:
  .form-group.border.p-4.mb-3
    = form.file_field :files, multiple: true, direct_upload: true, class: 'form-control-file'

  | Reward:
  #reward.border.p-4.mb-3
    .reward-fields[style="display: none;"]
      = form.fields_for :reward, @question.reward do |reward_form|
        .form-group
          = reward_form.label :title
          = reward_form.text_field :title, class: 'form-control'

        .form-group
          = reward_form.label :image
          = reward_form.file_field :image, direct_upload: true, accept: 'image/png,image/gif,image/jpeg', class: 'form-control-file'
    = link_to 'Add reward', '#', class: 'question-add-reward-link'

  div
    = form.submit

app/views/questions/show.html.slim
div class='card question question-#{@question.id}'
  div class='card-header'
    = @question.title
    - if @question.reward
      | &nbsp;
      = octicon 'ruby', class: 'reward'
  div class='card-body'
    div class='question-layout'
      div class='question-left'
        div class='vote'
          = render 'shared/voting', resource: @question, result: @question.vote_result_for(current_user)
      div class='question-right card-text'
        = @question.body
    div class='question-attached-links'
      = render @question.links
    div class='question-attached-files'
      = render 'shared/files', resource: @question

  - if current_user&.author_of?(@question)
    div class='card-footer'
      div class='question-author-links'
        = link_to "#", class: 'question-edit-link mr-2', title: 'Edit', data: { question_id: @question.id } do
          = octicon 'pencil', width: 16
        = link_to question_path(@question), title: 'Delete', method: :delete, data: { confirm: 'Are you sure?' } do
          = octicon 'trashcan', width: 16
      div class='question-edit'
        = render 'questions/edit_form', question: @question
div class='question-#{@question.id}-comments comments col col-md-10 offset-md-2 mt-3'
  = render @question.comments
  div class='new-comment-errors'
  - if user_signed_in?
    = render 'comments/form', resource: @question
    = link_to 'New comment', '#', class: 'new-comment-link', data: { commentable: "question-#{@question.id}" }
div class='answers mt-5 p-3'
  = render @question.answers
- if user_signed_in?
  div class='new-answer'
    = render 'answers/form', resource: [@question, @answer]

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% unless @question.errors.present? %>
  $('.question .card-header').html('<%= j @question.title %>');
  $('.question .card-text').html('<%= j @question.body %>');
  $('.question .question-attached-links').html('<%= render @question.links %>');
  $('.question .question-attached-files').html('<%= render 'shared/files', resource: @question %>');
  $('.question #question_files').val('');
  $('.question-author-links').show();
  $('.question-edit').html('<%= j render('questions/edit_form', question: @question) %>');
  <%= render 'shared/update_flash' %>
  scanForGists('.question')
<% end %>