config/routes.rb
Rails.application.routes.draw do
  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_delete
    end
  end

  concern :commentable do |options|
    resources :comments, { only: %i[create], shallow: true }.merge(options)
  end

  devise_for :users

  resources :questions do
    concerns :votable
    concerns :commentable, commentable_type: 'Question'

    resources :answers, shallow: true do
      concerns :votable
      concerns :commentable, commentable_type: 'Answer'

      patch :assign_as_best, on: :member
    end
  end

  resources :attachments, only: %i[destroy]

  resources :links, only: %i[destroy]

  resources :rewards, only: %i[index]

  root to: "questions#index"
end

app/views/shared/_errors.html.slim
- if resource.errors.any?
  = content_tag :div, class: 'row justify-content-center resource-errors' do
    div class="col col-md-6 ml-1 mr-1 alert alert-danger" role="alert"
      h5 class="alert-heading text-center"
        = "#{pluralize(resource.errors.count, 'error')} detected"
      hr
      ul class="list-group ml-4"
        - resource.errors.full_messages.each do |message|
          li class="list-item"
            = message

app/views/shared/_files.html.slim
- if resource.files.attached?
  - resource.files.each do |file|
    = " | "
    = link_to file.filename.to_s, url_for(file)
    - if current_user&.author_of?(resource)
      | &nbsp;
      = link_to attachment_path(file), title: 'Delete', method: :delete, remote: true, data: { confirm: 'Are you sure?' } do
        = octicon :x, class: 'attachment_delete'
  = " | "

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  div class="row justify-content-center"
    = content_tag :div, class: "col col-md-4 alert flash-alert #{key_to_style(key)} alert-dismissible fade show", role: 'alert' do
      = message
      button type="button" class="close" data-dismiss="alert" aria-label='Close'
        span aria-hidden="true"
          | &times;

app/views/shared/_header.html.slim
nav class="header navbar navbar-light bg-light"
  = link_to 'Questions and Answers', root_path, class: "navbar-brand"
  span class="navbar-text"
    - if user_signed_in?
      = "#{current_user.email} | "
      = link_to 'Rewards', rewards_path
      = " | "
      = link_to 'Log out', destroy_user_session_path, method: :delete
    - else
      = link_to 'Register', new_user_registration_path
      = " | "
      = link_to 'Login', new_user_session_path

app/views/shared/_update_flash.js.erb
$('.flash-messages').html('<%= render 'shared/flash' %>');
flashFadeOut();

app/views/shared/_voting.html.slim
.vote-up-control
  - if user_signed_in? && !current_user.author_of?(resource)
    = vote_control(resource, 'vote_up', result, 'triangle-up')
  - else
    = octicon 'triangle-up', width: 24, class: 'voting-disabled'
.vote-score
  = resource.vote_score
.vote-down-control
  - if user_signed_in? && !current_user.author_of?(resource)
    = vote_control(resource, 'vote_down', result, 'triangle-down')
  - else
    = octicon 'triangle-down', width: 24, class: 'voting-disabled'