config/routes.rb
Rails.application.routes.draw do
  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_delete
    end
  end

  concern :commentable do |options|
    resources :comments, { only: %i[create], shallow: true }.merge(options)
  end

  devise_for :users

  resources :questions do
    concerns :votable
    concerns :commentable, commentable_type: 'Question'

    resources :answers, shallow: true do
      concerns :votable
      concerns :commentable, commentable_type: 'Answer'

      patch :assign_as_best, on: :member
    end
  end

  resources :attachments, only: %i[destroy]

  resources :links, only: %i[destroy]

  resources :rewards, only: %i[index]

  root to: "questions#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable, Commentable

  default_scope { order(best: :desc, id: :asc) }

  has_many :links, dependent: :destroy, as: :linkable

  belongs_to :question
  belongs_to :author, class_name: 'User'

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_commit :broadcast_new_answer, on: :create

  def assign_as_best!
    ActiveRecord::Base.transaction do
      question.answers.update_all(best: false)
      update!(best: true)
      question.assign_reward!(author)
    end
  end

  private

  def broadcast_new_answer
    BroadcastObjectCreationJob
      .perform_later("new_answer_events_for_question_#{self.question_id}", answer: ::AnswerSerializer.new(self).as_json)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :find_question, only: %i[create]
  before_action :find_answer, only: %i[update destroy assign_as_best]

  def create
    @answer = @question.answers.new(answer_params)
    @answer.author = current_user
    if @answer.save
      flash.now.notice = 'Answer successfully created'
    end
  end

  def update
    if current_user.author_of?(@answer)
      @answer.update(answer_params)
      flash.now.notice = 'Answer successfully updated'
    else
      flash.now.alert = "You don't have permission to do that"
    end
  end

  def destroy
    if current_user.author_of?(@answer)
      @answer.destroy
      flash.now.notice = 'Answer successfully deleted'
    else
      flash.now.alert = "You don't have permission to do that"
    end
  end

  def assign_as_best
    if current_user.author_of?(@answer.question)
      @answer.assign_as_best!
      flash.now.notice = 'Answer successfully made best'
    else
      flash.now.alert = "You don't have permission to do that"
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  div class='answer-#{answer.id} p-2'
    div class='answer-layout'
      div class='answer-left'
        div class='vote'
          = render 'shared/voting', resource: answer, result: answer.vote_result_for(current_user)
        - if answer.best?
          = octicon 'check', width: 20, class: 'best-answer'
      div class='answer-right'
        p= answer.body
        div class='answer-attached-links'
          = render answer.links
        div class='answer-attached-files'
          = render 'shared/files', resource: answer

      div class='answer-management'
        - if current_user&.author_of?(answer.question)
          div class='question-author-links mb-2'
            - unless answer.best?
              = link_to assign_as_best_answer_path(answer), method: :patch, title: 'Make best', class: 'mr-2', remote: true do
                = octicon 'check', width: 16
        - if current_user&.author_of?(answer)
          div class='answer-author-links'
            = link_to "#", title: 'Edit', class: 'answer-edit-link mr-2', data: { answer_id: answer.id } do
              = octicon 'pencil', width: 16
            = link_to answer_path(answer), title: 'Delete', method: :delete, remote: true, data: { confirm: 'Are you sure?' } do
              = octicon 'trashcan', width: 16
          = render 'answers/edit_form', answer: answer
    hr
    div class='answer-#{answer.id}-comments comments col col-md-10 offset-md-2 mt-3'
      = render answer.comments
      div class='new-comment-errors'
      - if user_signed_in?
        = render 'comments/form', resource: answer
        = link_to 'New comment', '#', class: 'new-comment-link', data: { commentable: "answer-#{answer.id}" }

app/views/answers/_edit_form.html.slim
div class='answer-errors'
= form_with model: answer, class: 'answer-edit-form', html: { style: 'display:none;' } do |form|
  div class='form-group'
    = form.label :body, 'Your answer'
    = form.text_area :body, class: 'form-control'

  | Links:
  #links.border.p-4.mb-3
    = form.fields_for :links do |link|
      - unless link.object.persisted?
        = render 'links/link_fields', f: link
    span
      = link_to_add_association 'Add link', form, :links, partial: 'links/link_fields'

  | Files:
  .form-group.border.p-4
    = form.file_field :files, multiple: true, direct_upload: true, class: 'form-control-file'

  div
    = form.submit 'Save'

app/views/answers/_form.html.slim
div class='new-answer-errors'
= form_with model: resource, class: 'new-answer-form' do |form|
  div class='form-group'
    = form.label :body, 'New answer'
    = form.text_area :body, class: 'form-control'

  | Links:
  #links.border.p-4.mb-3
    = form.fields_for :links do |link|
      = render 'links/link_fields', f: link
    span
      = link_to_add_association 'Add link', form, :links, partial: 'links/link_fields'

  | Files:
  .form-group.border.p-4
    = form.file_field :files, multiple: true, direct_upload: true, class: 'form-control-file'
  div
    = form.submit

app/views/answers/assign_as_best.js.erb
<% if @answer.best? %>
  $('.answers').html('<%= j render @answer.question.answers %>')
  <%= render 'shared/update_flash' %>
<% end %>

app/views/answers/create.js.erb
$('.new-answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer').html('<%= j render('answers/form', resource: [@question, @question.answers.build]) %>');
  <%= render 'shared/update_flash' %>
  scanForGists('<%= ".answer-#{@answer.id}" %>');
  subscribeForComments('answer', <%= @answer.id %>);
<% end %>

app/views/answers/destroy.js.erb
<% unless @answer.persisted? %>
  $('.answer-<%= @answer.id %>').remove();
<% end %>

<%= render 'shared/update_flash' %>

app/views/answers/new.html.slim
h1 Create new Answer
= form_with model: [@question, @answer], local: true do |form|
  div
    = form.label :body
    = form.text_area :body

  div
    = form.submit

app/views/answers/update.js.erb
$('<%= ".answer-#{@answer.id}" %> .answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $('<%= ".answer-#{@answer.id}" %>').replaceWith('<%= j render @answer %>');
  <%= render 'shared/update_flash' %>
  scanForGists('<%= ".answer-#{@answer.id}" %>');
<% end %>