config/routes.rb
Rails.application.routes.draw do
  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_delete
    end
  end

  concern :commentable do |options|
    resources :comments, { only: %i[create], shallow: true }.merge(options)
  end

  devise_for :users

  resources :questions do
    concerns :votable
    concerns :commentable, commentable_type: 'Question'

    resources :answers, shallow: true do
      concerns :votable
      concerns :commentable, commentable_type: 'Answer'

      patch :assign_as_best, on: :member
    end
  end

  resources :attachments, only: %i[destroy]

  resources :links, only: %i[destroy]

  resources :rewards, only: %i[index]

  root to: "questions#index"
end

app/models/link.rb
class Link < ApplicationRecord
  default_scope { order(:id) }

  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates :url, url: true
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :find_link, only: %i[destroy]

  def destroy
    @resource = @link.linkable
    if current_user.author_of?(@resource)
      @link.destroy
      flash.now.notice = 'Link successfully deleted'
    else
      flash.now.alert = "You don't have permission to do that"
    end
  end

  private

  def find_link
    @link = Link.find(params[:id])
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_link.html.slim
- if link.persisted?
  .attached-link
    - if current_user&.author_of?(link.linkable)
      = link_to link_path(link), title: 'Delete', method: :delete, remote: true, data: { confirm: 'Are you sure?' } do
        = octicon :x, class: 'attachment_delete'
      | &nbsp;
    = link_to link.name, link.url

app/views/links/_link_fields.html.slim
div class='nested-fields'
  div class='form-group'
    = f.label :name
    = f.text_field :name, class: 'form-control'

  div class='form-group'
    = f.label :url
    = f.url_field :url, class: 'form-control'

  = link_to_remove_association "Remove Link", f

app/views/links/destroy.js.erb
<% unless @link.persisted? %>
  var cssSelector = '<%= generate_css_selector(@resource, 'links') %>';
  $(cssSelector).html('<%= render @resource.links %>');
<% end %>

<%= render 'shared/update_flash' %>
scanForGists(cssSelector);